### ISSUE TITLE
out of order packets

### ISSUE THREAD

**Issue by openserli** [svpcom/wifibroadcast#1]
hi, have wifibroadcast process packet out or order case ?

**Comment by svpcom** [comment]
Yes, wifibroadcast can process out of order packets. Default ring buffer depth is 40 FEC blocks 8 packets each.

**Comment by openserli** [comment]
thanks, i want add your fec part to my voip video call app, and my app has a video jitter buffer, do you have any suggest on how to use you fec part with my video app?
