### ISSUE TITLE
Other SOC compatability

### ISSUE THREAD

**Issue by terial** [svpcom/wifibroadcast#10]
Hey svpcom, hope all is well and your projects have been going well. Will your version of Wifibroadcast work with any other devices that raspberry pi? I am looking into something that has usb 3.0 like the beagleboard x15.

Thanks.

**Comment by svpcom** [comment]
Wifibroadcast is not tied to any GPU - it operates with UDP  packets. But to get RTP stream you need a video encoder (with encode  raw data from camera to x264 stream). In my case RPI is only used for  video encoding (becase RPI Zero is too slow to do anything else) and all  other tasks (including wifibroadcast) are done by other board (NanoPI  NEO2).
--

**Comment by svpcom** [comment]
Added to FAQ

**Comment by terial** [comment]
Thanks for the response. Sorry for my lack of understanding it sounds like wifibroadcast does not care about what device it is run on, I would just need to use something like gstreamer on the beagleboard x15?

https://beagleboard.org/x15

**Comment by svpcom** [comment]
Yes, you need gstreamer or ffmpeg to get RTP stream from camera
