### ISSUE TITLE
name clash

### ISSUE THREAD

**Issue by fnoop** [svpcom/wifibroadcast#11]
Hi, great to see this project take up from and improve on the old befinitiv project.  It's a bit confusing to have the same name, particularly for systems that want to offer both as an option.   Might be an idea to rename the project to avoid confusion?

**Comment by svpcom** [comment]
Original wifibroadcast (https://befinitiv.wordpress.com/wifibroadcast-analog-like-transmission-of-live-video-data/) IMHO dead. So now only live ez-wifibroadcast and my version.

**Comment by fnoop** [comment]
It's just people associate 'wifibroadcast' with befinitiv, and that code is still used and alive by people even if not developed.  But your choice of course, thanks for your new version :)
