### ISSUE TITLE
Packets lost while running in virtual machine with NAT network[BUG]

### ISSUE THREAD

**Issue by iamfaith** [svpcom/wifibroadcast#112]
**Describe the bug**
Packets lost while running in the virtual machine with NAT network. Both Rx and Tx are using rt28xx wifi cards.

**To Reproduce**

1. run RX in virtual box with NAT network with rt28xx wifi cards.
2. run TX in raspberry pi zero with rt28xx wifi cards.

the output result is like this.

![image](https://user-images.githubusercontent.com/16201784/107173606-23066580-6a03-11eb-89f0-e1b4d8ac226b.png)

![image](https://user-images.githubusercontent.com/16201784/107173644-429d8e00-6a03-11eb-875b-fe965a17166e.png)

**Comment by iamfaith** [comment]
I found the problem. It 's because i am using the monitor interface. Now I close it

**Comment by iamfaith** [comment]
pi(gstreamer) --> pi(wfb_tx:rt:28xxx) -------------(radio)---------------> virtual box ubuntu(wfb_rx: rt28xxx)--(NAT)---> mac os(gstreamer)
This gets a really bad video.

If pi(gstreamer)  --(wifi)----> mac os(gstreamer), pretty good video

**Comment by svpcom** [comment]
What is your gstreamer pipeline?

**Comment by svpcom** [comment]
What frequency channel do you use?

**Comment by iamfaith** [comment]
> What frequency channel do you use?

channel 6 with 20hz

On pi zero:  gst-launch-1.0  filesrc location=a.mp4 ! decodebin ! omxh264enc ! rtph264pay ! udpsink host=127.0.0.1 port=5600

On mac:  
 gst-launch-1.0 udpsrc port=5600 caps='application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264' \
               ! rtph264depay ! avdec_h264 ! clockoverlay valignment=bottom ! autovideosink fps-update-interval=1000 sync=false

**Comment by iamfaith** [comment]
Dear svpcom, 

I found the problem is that in this channel, there are 16 APs! It seems there are interferences. Since I live in city, each channel seems really busy. is there any way to overcome this?

**Comment by svpcom** [comment]
Yes, use 5.8Ghz band

**Comment by svpcom** [comment]
2.4 GHz is not usable in cities

**Comment by iamfaith** [comment]
> 2.4 GHz is not usable in cities

But there are many 5G signals from wifi as well. Why will 5G Hz be usable?

**Comment by svpcom** [comment]
In 2.4 band only 3 independent channels. In 5.8 - much more https://en.wikipedia.org/wiki/List_of_WLAN_channels

**Comment by svpcom** [comment]
Also most of consumer radio devices use 2.4 band (bluetooth, auto alarms, microwave ovens etc)
