### ISSUE TITLE
Memory leak in fec.c

### ISSUE THREAD

**Issue by xavier862** [svpcom/wifibroadcast#119]
Hi Vasily,
There is a memory leak in your `fec.c`, specifically in function `_invert_mat()`. The four allocations

    unsigned* indxc = (unsigned*) malloc (k * sizeof(unsigned));
    unsigned* indxr = (unsigned*) malloc (k * sizeof(unsigned));
    unsigned* ipiv = (unsigned*) malloc (k * sizeof(unsigned));
    gf *id_row = NEW_GF_MATRIX (1, k);

are never released.

[An updated fec.c](https://github.com/tahoe-lafs/zfec/blob/master/zfec/fec.c) was actually released by the Tahoe-LAFS community three years ago. However you cannot use it as is, because they also changed the signature of `fec_encode()` adding two parameters, which makes it incompatible with your `tx.cpp`.

Therefore the easiest for you is to update your own `fec.c` by adding those four lines right at the end of `_invert_mat()`:

    free(indxc);
    free(indxr);
    free(ipiv);
    free(id_row);

Hope that helps !
Xavier

**Comment by svpcom** [comment]
@xavier862 Thanks!
