### ISSUE TITLE
nvidia jetpack rtl8812au monitor no capture

### ISSUE THREAD

**Issue by amtcvx** [svpcom/wifibroadcast#126]
Hello, 

I am running wifibroadcast successfull with rt2800usb and 88XXau, on raspberry (Raspian Buster) pi0, pi3B+, pi4, PC desktop (Ubuntu 1804), and Nvidia Nano, Xavier NX (Jetpack 4.5.0).

However, for Nvidias with 88XXau the wlan0 interface do not receive messages with svpcom/rtl8812au/v5.6.4.2.
while there are received with aircrack-ng/rtl8812au/v5.7.0 (5.9.3.2).
But messages are not more recognized by wifibroadcast with version
rx.cpp => "unknown encapsulation"

How can I use wifibroadcast with rtl8812au on the NVIDIA boards ?

Thank you for your support.
XP

**Comment by svpcom** [comment]
See https://github.com/svpcom/wifibroadcast/discussions/123
Remove rtl8812au.ko driver
