### ISSUE TITLE
Rx Tx Wifi Hardware

### ISSUE THREAD

**Issue by Tyrrx** [svpcom/wifibroadcast#13]
Hello,
I have some questions regarding to the hardware setup:
As the ALFA AWUS051NH v2 has reached EOL is there any way to use the Alfa Network AWUS036ACH?
Due to the weak performance the Rasperry Pi Zero does not seem to work as standalone Tx setup (USB cam / RPI cam -> RPI -> Wifi). Furthermore the Raspberry Pi 3 his very huge and heavy, which means it is no opportunity (about 44g).
So what about these boards:
NanoPi-NEO2		http://nanopi.org/NanoPi-NEO2_Feature.html
Banana Pi M2 Zero	http://www.banana-pi.org/bpi-zero.html
NanoPi-NEO-Air	http://nanopi.org/NanoPi-NEO-air_Feature.html
Nanopi-Duo		http://nanopi.org/NanoPi-Duo_Feature.html
Nanopi-NEO-Plus2	http://nanopi.org/NanoPi-NEO-Plus2_Feature.html
NanoPi-NEO		http://nanopi.org/NanoPi-NEO_Feature.html
NanoPi-NEO2		http://nanopi.org/NanoPi-NEO2_Feature.html
Nanopi-NEO-Core2	http://nanopi.org/NanoPi-NEO-Core2_Feature.html
Is there something usable as Tx or do you have any other low price and low weight boards that could be used?
I am very new to the Rasperry Pi world so you have to help me out a little bit. :)
Regards
David

**Comment by svpcom** [comment]
I use NanoPI NEO2 for TX and RX and RPI Zero + Pi camera only as HW h264 codec.
I don't have AWUS036ACH, so I don't know its status, but https://wikidevi.com/wiki/ALFA_Network_AWUS036ACH says that it has different chip and different driver.

**Comment by svpcom** [comment]
I use WiFi HW compatible with rt2800usb driver.

**Comment by svpcom** [comment]
Yes, but if your wifi card (Tx) is too powerful (for example 1W output) you need to wire +5v directly to UBEC (usb port has power limit)

**Comment by Tyrrx** [comment]
I would connect the Tx to a UBEC anyway because even my computer has only 100mA usb current.
What do you think about the Orange Pi Zero? it has nearly the same size as the Nanopi Neo2 but is a littel bit cheaper (due to its cpu) but it seems to support more operation systems e.g. raspbian.
The only real disadvantage i found was: it has only one usb 2.0 host and one usb otg.
I am not sure if that could work with a hd usb cam und the usb wifi.

**Comment by Tyrrx** [comment]
Okay i just saw an Orange Pi Zero vs Nanopi Neo benchmark and its absolutely going to be a Nanopi Neo2.
By the way which RC do you use?

**Comment by Tyrrx** [comment]
What does the camera need to work properly with the nanopi neo2? Because at the moment i cant find a cheep 720p or 1080p camera that could work with the neo2.

**Comment by Tyrrx** [comment]
I have read that the NanoPi Fire2 does not support hardware h.264 encoding/decoding that could become a real problem..

**Comment by svpcom** [comment]
My setup is:
```
pi camera -[CSI bus]-> RPI Zero -[usb]->  NanoPI NEO2 -[usb]-> AWUS052NH
```
I use RPI zero as HW h264 encoder and NaniPI NEO2 as main vehicle computer (running wifibroadcast, mavlink router, etc). If you don't have RPI you can get h264 capable webcam (Logitech camera C920). But I prefer to use PI camera with good optics (CS lenses) and PI Zero as HW h264 codec. Other boards (odroid c0/c1/c2) has h264 codecs but they have **very poor** quality to compression ratio. SW-only codec is too heavy to run on NEO2 at 1080p.

**Comment by svpcom** [comment]
GStreamer setup for C920:
```
gst-launch-1.0 uvch264src device=/dev/video0 initial-bitrate=4000000 average-bitrate=4000000 iframe-period=1000 name=src auto-start=true \
            src.vidsrc ! queue ! video/x-h264,width=1920,height=1080,framerate=30/1 ! h264parse ! rtph264pay ! udpsink host=localhost port=5600
```

**Comment by Tyrrx** [comment]
Do you know how to use the nanopi fire 3 with the DVP Camera CAM500B from here: http://wiki.friendlyarm.com/wiki/index.php/NanoPi_Fire3#Connect_to_DVP_Camera_CAM500B together with wifibroadcast.
At the moment i get this when i check for the camera devices:
crw-rw----+ 1 root video 81, 1 Jun 14 14:04 /dev/video15
crw-rw----+ 1 root video 81, 0 Jun 14 14:04 /dev/video14
The problem is I dont know how to setup gst now.

**Comment by svpcom** [comment]
Query camera settings: v4l2-ctl -d /dev/video0 --all
If it has h264 source use gst pipeline like for Logitech C920

**Comment by Tyrrx** [comment]
I tried to use ffmpeg on video14/15 to take a test picture but it says on both no video capture device and video0 does not exist.

**Comment by Tyrrx** [comment]
Okay the problem seems to be that the current friendly core version with 4.4 kernel does not yet (or not) support the dvp camera.

**Comment by Tyrrx** [comment]
Okay I found out that the Nanopi Fire 3 does not really support the Cam500B. Dont think about buying it.
Mybe I try to use the Nanopi Air with the cam or I buy a Neo2 with Logitech c920.
