### ISSUE TITLE
Patched Nanopi neo2 Image

### ISSUE THREAD

**Issue by Tyrrx** [svpcom/wifibroadcast#19]
Hello,
you said that you have a patched nanopi neo2 kernel, Could you create and upload an image of it because I have difficulties with patching the Kernel for the Neo2?

That would be great :)
David

**Comment by svpcom** [comment]
As source SD image you can use ``official-ROMs/nanopi-neo2_sd_friendlycore-xenial_4.14_armhf_YYYYMMDD.img.zip``  from http://download.friendlyarm.com/nanopineo2 or armbian image for NEO2 (if you don't trust neo2 vendor images)

**Comment by Tyrrx** [comment]
what about this? make sunxi_arm64_defconfig ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-

**Comment by svpcom** [comment]
Does you card support 30dBm output? Was CRDA patch applied? Run: ``iw reg get``
