### ISSUE TITLE
 dpkg: error: cannot access archive 'wifibroadcast*.deb': No such file or directory

### ISSUE THREAD

**Issue by mmucahitkaya** [svpcom/wifibroadcast#217]
Hi, When i try to install wifibroadcast, i got this error.

dpkg: error: cannot access archive 'wifibroadcast*.deb': No such file or directory

![image](https://user-images.githubusercontent.com/39586436/168495143-239fff2f-e0a5-4b72-b550-3774d95bed4f.png)

**Comment by svpcom** [comment]
Check that `make deb` finished without errors

**Comment by mmucahitkaya** [comment]
I can't to fix this error. Here is screenshot for `sudo make deb`

![image](https://user-images.githubusercontent.com/39586436/168495484-6bd6f679-addc-4d87-a620-710203b89ff0.png)

**Comment by svpcom** [comment]
`apt install python3-all dh-python debhelper`

**Comment by mmucahitkaya** [comment]
Oh got, it's done. Thank you very much 🙂

![image](https://user-images.githubusercontent.com/39586436/168495815-4563ecb1-d930-426e-ab86-7360ffbbbbfd.png)
