### ISSUE TITLE
android support possible (cmake/cross-compile)

### ISSUE THREAD

**Issue by mattgorski** [svpcom/wifibroadcast#23]
Just wondering if you have ever tried to build wifibroadcast/libsodium/libpcap for running inside android with iw and iwconfig.

Seems this would be possible running QgroundControl and udp video on android device.  Probably no python so no telem but video should be feasible.

**Comment by mattgorski** [comment]
Just saw this response thanks for the tip I ended up using Linux deploy but i may try the chroot with a custom init also,  thanks again.

**Comment by imagemlt** [comment]
> Just saw this response thanks for the tip I ended up using Linux deploy but i may try the chroot with a custom init also, thanks again.

how do you compile wifi card drivers under chroot environment

**Comment by svpcom** [comment]
> > Just saw this response thanks for the tip I ended up using Linux deploy but i may try the chroot with a custom init also, thanks again.
> 
> how do you compile wifi card drivers under chroot environment

`make KVER=your_kernel_version`
