### ISSUE TITLE
Support of BananaPi

### ISSUE THREAD

**Issue by QiXuanWang** [svpcom/wifibroadcast#25]
I remember I saw you listed hardware comparison but I couldn't find it right now. The impression is that this project doesn't really care too much about computer hardware?

I was wondering if you could support BPI? You'll have some advanced/expensive choice regarding computing power which could be better fit when needed.

**Comment by svpcom** [comment]
If bananapi supports modern kernel (4.x.x) and has usb ports it should works. If kernel is old (3.x.x) then you need to apply additional patches to enable packet injection.

**Comment by QiXuanWang** [comment]
I see. I think it could same system as RPI3. Just a FYI so in case your project evolved into that stage that a strong hardware would be helpful then there is an option. I'll probably try it out when I fully understand your process.

**Comment by svpcom** [comment]
My primary hw setup is NanoPI NEO2

**Comment by QiXuanWang** [comment]
No problem. Please close this since it's not an issue.
