### ISSUE TITLE
Dev question - how can I test the library by emulating the wifi bridge

### ISSUE THREAD

**Issue by Consti10** [svpcom/wifibroadcast#66]
Hello,
In the tx code there is the 'UdpTransmitter' class. I assume its purpose is to test the library without using wifi as link between tx and rx (since it is wrapped into #ifdef DEBUG_TX , too)

However, I cannot find its equivalent in the rx code.

Any ideas ?

**Comment by svpcom** [comment]
Yes, it for debug without hardware. Use rx in `aggregator` mode.
```
...
Remote (aggregator): ./wfb_rx -a server_port [-K rx_key] [-k RS_K] [-n RS_N] [-c client_addr] [-u client_port] [-l log_interval]
...
```

**Comment by svpcom** [comment]
See https://github.com/svpcom/wifibroadcast/wiki/wfb_tx-and-wfb_rx-reference for reference

**Comment by Consti10** [comment]
Thanks it worked.
