### ISSUE TITLE
Dev Question - is wpacket_hdr_t redundant (packet_size)

### ISSUE THREAD

**Issue by Consti10** [svpcom/wifibroadcast#67]
Hello,
What's the reasoning behind writing the packet size in each wb packet ?

I'd guess it is redundant, since the packet size can be calculated on rx by substracting header size from packet size ?

This way we get 2 more bytes into each packet.

**Comment by Consti10** [comment]
I think it is an relict of how you wrote the fec encoder / decoder part.
But there it can be stored somewhere else, and must not be included in the actual packet going out.

**Comment by Consti10** [comment]
I think I understand now why the packet size is written with each fec packet:
If a data packet is lost, and this data packet is reconstructed by FEC, the information where the actual data of this packet is and where the '0' padding begins cannot be recovered.
So this information needs to be reconstructed with the FEC step, and therefore needs to stand in the packet

**Comment by svpcom** [comment]
yes

**Comment by Consti10** [comment]
Pretty smart :)
