### ISSUE TITLE
What's involved in 'patching the kernel'?

### ISSUE THREAD

**Issue by tictag** [svpcom/wifibroadcast#9]
@svpcom I note in installation instructions contained [here](https://dev.px4.io/en/qgc/video_streaming_wifi_broadcast.html), in "Software Setup" bullet (3) I have to "Patch your kernel". I am not a software developer but am a quick study and I understand that this means downloading the kernel source code from the [www.raspberrypi.org github repository](https://github.com/raspberrypi), using the "patch" application to modify that source code, then building the kernel, presumably to end up with a new "kernel.img" file.

- Firstly, have I understood the 4.75 million web pages I've had to read to to be able to say all that! ;)
- Secondly, building the entire kernel for some minor changes seems like a lot of effort (and processor time), is there an easier way, for example, just "make"ing the files that are changing?

Appreciate you helping out a noob here.

**Comment by svpcom** [comment]
You can use prebuilt kernel for Raspberry PI from [ez-wifibroadcast](https://github.com/bortek/EZ-WifiBroadcast/wiki). Just download their SD-card image and replace wifibroadcast binaries. I don't use RPI for TX or RX (use NanoPI NEO instead) so I don't have prebuilt kernel for RPI

**Comment by tictag** [comment]
Appreciate your help, thank you and will do. Just for my own knowledge, is my understanding of patching the kernel described above correcti(ish)?

**Comment by svpcom** [comment]
Yes, you are correct. You need to apply patches to kernel sources and rebuild kernel and modules.

**Comment by geofrancis** [comment]
how did you get it to work on another board? i thought that wifibroadcast was tied to the pi gpu?
